import { CHECKS, type CheckName, type CheckStatus, type ProbeReport } from "./probe.js";

const ICON: Record<CheckStatus, string> = {
  pass: "✅",
  fail: "❌",
  unsupported: "➖",
  error: "⚠️",
  skipped: "·",
};

/** Renders probe results as the capability matrix in docs/acp-capabilities.md. */
export function renderMarkdown(
  reports: ProbeReport[],
  meta: { host: string; date: string },
): string {
  const names = Object.keys(CHECKS) as CheckName[];
  const lines: string[] = [];
  lines.push("# ACP capability matrix", "");
  lines.push(`Generated by \`pnpm probe\` on ${meta.host}, ${meta.date}.`);
  lines.push("What each check means and why it matters: [acp-probe.md](acp-probe.md).", "");
  lines.push(
    `Legend: ${ICON.pass} works · ${ICON.fail} broken · ${ICON.unsupported} not offered · ${ICON.error} error · ${ICON.skipped} not reached`,
    "",
  );
  lines.push(`| Check | ${reports.map((r) => r.agent.id).join(" | ")} |`);
  lines.push(`|---|${reports.map(() => ":-:").join("|")}|`);
  for (const name of names) {
    lines.push(
      `| ${CHECKS[name]} | ${reports.map((r) => ICON[r.checks[name].status]).join(" | ")} |`,
    );
  }
  lines.push("");
  for (const r of reports) {
    lines.push(`## ${r.agent.name}`, "");
    if (r.info) {
      lines.push(`- Agent: ${r.info.agentInfo ?? "unknown"} (ACP v${r.info.protocolVersion})`);
      lines.push(
        `- session/load: ${r.info.loadSession ? "yes" : "no"}; session capabilities: ${list(r.info.sessionCapabilities)}`,
      );
      lines.push(`- Prompt content: ${list(r.info.promptCapabilities)}`);
      lines.push(`- Agent modes: ${list(r.info.modes)}`);
      lines.push(`- Config options: ${list(r.info.configOptions)}`);
      lines.push(`- Auth methods: ${list(r.info.authMethods)}`);
      lines.push("");
    }
    lines.push("| Check | Result | Detail |", "|---|:-:|---|");
    for (const name of names) {
      const c = r.checks[name];
      const ms = c.ms != null ? ` (${(c.ms / 1000).toFixed(1)}s)` : "";
      lines.push(`| ${CHECKS[name]} | ${ICON[c.status]} | ${escapeCell(c.detail)}${ms} |`);
    }
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

/** Compact console summary. */
export function renderSummary(report: ProbeReport): string {
  const names = Object.keys(CHECKS) as CheckName[];
  return [
    `${report.agent.name}`,
    ...names.map(
      (n) =>
        `  ${ICON[report.checks[n].status]} ${CHECKS[n].padEnd(22)} ${report.checks[n].detail}`,
    ),
  ].join("\n");
}

function list(items: string[]): string {
  return items.length ? items.map((i) => `\`${i}\``).join(", ") : "none";
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}
